//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONTAP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class quanlybanlaptop2Entities : DbContext
    {
        public quanlybanlaptop2Entities()
            : base("name=quanlybanlaptop2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tblChiTietHD> tblChiTietHD { get; set; }
        public DbSet<tblChiTietPhieuNhap> tblChiTietPhieuNhap { get; set; }
        public DbSet<tblChiTietPhieuXuat> tblChiTietPhieuXuat { get; set; }
        public DbSet<tblChiTietThietBi> tblChiTietThietBi { get; set; }
        public DbSet<tblGiaoHang> tblGiaoHang { get; set; }
        public DbSet<tblHoaDon> tblHoaDon { get; set; }
        public DbSet<tblKhachHang> tblKhachHang { get; set; }
        public DbSet<tblLoaiNhanVien> tblLoaiNhanVien { get; set; }
        public DbSet<tblLoaiThietBi> tblLoaiThietBi { get; set; }
        public DbSet<tblNhaCungCap> tblNhaCungCap { get; set; }
        public DbSet<tblNhanVien> tblNhanVien { get; set; }
        public DbSet<tblNhomTB> tblNhomTB { get; set; }
        public DbSet<tblPhieuNhapHang> tblPhieuNhapHang { get; set; }
        public DbSet<tblPhieuXuatHang> tblPhieuXuatHang { get; set; }
        public DbSet<tblTaiKhoan> tblTaiKhoan { get; set; }
        public DbSet<tblThanhToan> tblThanhToan { get; set; }
        public DbSet<tblThietBi> tblThietBi { get; set; }
    }
}
