//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONTAP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGiaoHang
    {
        public int MaHD { get; set; }
        public int MaVanChuyen { get; set; }
        public string TenNguoiNhan { get; set; }
        public string DiaChi1 { get; set; }
        public string DiaChi2 { get; set; }
        public string DiaChi3 { get; set; }
        public string MaDonViVanChuyen { get; set; }
        public string SoDT1 { get; set; }
        public string SoDT2 { get; set; }
        public string Email { get; set; }
    
        public virtual tblHoaDon tblHoaDon { get; set; }
    }
}
