//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONTAP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblKhachHang
    {
        public tblKhachHang()
        {
            this.tblHoaDon = new HashSet<tblHoaDon>();
        }
    
        public int MaKH { get; set; }
        public string TenKH { get; set; }
        public System.DateTime NgaySinh { get; set; }
        public string GioiTinh { get; set; }
        public string DienThoai { get; set; }
        public string DiaChi { get; set; }
        public string Email { get; set; }
        public string TaiKhoan { get; set; }
    
        public virtual ICollection<tblHoaDon> tblHoaDon { get; set; }
        public virtual tblTaiKhoan tblTaiKhoan { get; set; }
    }
}
