//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONTAP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLoaiNhanVien
    {
        public tblLoaiNhanVien()
        {
            this.tblNhanVien = new HashSet<tblNhanVien>();
        }
    
        public int MaLoaiNV { get; set; }
        public string TenLoaiNV { get; set; }
    
        public virtual ICollection<tblNhanVien> tblNhanVien { get; set; }
    }
}
