//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONTAP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLoaiThietBi
    {
        public tblLoaiThietBi()
        {
            this.tblThietBi = new HashSet<tblThietBi>();
        }
    
        public int MaLoai { get; set; }
        public string TenLoai { get; set; }
    
        public virtual ICollection<tblThietBi> tblThietBi { get; set; }
    }
}
