//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONTAP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNhaCungCap
    {
        public tblNhaCungCap()
        {
            this.tblPhieuNhapHang = new HashSet<tblPhieuNhapHang>();
            this.tblThietBi = new HashSet<tblThietBi>();
        }
    
        public int MaNCC { get; set; }
        public string TenNCC { get; set; }
        public string DiaChi { get; set; }
        public string DienThoai { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<tblPhieuNhapHang> tblPhieuNhapHang { get; set; }
        public virtual ICollection<tblThietBi> tblThietBi { get; set; }
    }
}
