//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONTAP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNhanVien
    {
        public tblNhanVien()
        {
            this.tblHoaDon = new HashSet<tblHoaDon>();
            this.tblPhieuNhapHang = new HashSet<tblPhieuNhapHang>();
            this.tblPhieuXuatHang = new HashSet<tblPhieuXuatHang>();
        }
    
        public int MaNV { get; set; }
        public string TenNV { get; set; }
        public string DiaChi { get; set; }
        public string DienThoai { get; set; }
        public string Email { get; set; }
        public int MaLoaiNV { get; set; }
        public string TaiKhoan { get; set; }
    
        public virtual ICollection<tblHoaDon> tblHoaDon { get; set; }
        public virtual tblLoaiNhanVien tblLoaiNhanVien { get; set; }
        public virtual tblTaiKhoan tblTaiKhoan { get; set; }
        public virtual ICollection<tblPhieuNhapHang> tblPhieuNhapHang { get; set; }
        public virtual ICollection<tblPhieuXuatHang> tblPhieuXuatHang { get; set; }
    }
}
