//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONTAP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPhieuXuatHang
    {
        public tblPhieuXuatHang()
        {
            this.tblChiTietPhieuXuat = new HashSet<tblChiTietPhieuXuat>();
        }
    
        public int MaPhieuXH { get; set; }
        public int MaNVXuatHang { get; set; }
        public int MaHD { get; set; }
        public System.DateTime NgayXuat { get; set; }
    
        public virtual ICollection<tblChiTietPhieuXuat> tblChiTietPhieuXuat { get; set; }
        public virtual tblNhanVien tblNhanVien { get; set; }
    }
}
