//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONTAP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPhieuNhapHang
    {
        public tblPhieuNhapHang()
        {
            this.tblChiTietPhieuNhap = new HashSet<tblChiTietPhieuNhap>();
        }
    
        public int MaPhieuNH { get; set; }
        public int MaNVNhanHang { get; set; }
        public int MaNCC { get; set; }
        public double TongTien { get; set; }
        public System.DateTime NgayNhap { get; set; }
    
        public virtual ICollection<tblChiTietPhieuNhap> tblChiTietPhieuNhap { get; set; }
        public virtual tblNhaCungCap tblNhaCungCap { get; set; }
        public virtual tblNhanVien tblNhanVien { get; set; }
    }
}
