//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONTAP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblThietBi
    {
        public tblThietBi()
        {
            this.tblChiTietThietBi = new HashSet<tblChiTietThietBi>();
        }
    
        public int MaTB { get; set; }
        public string TenTB { get; set; }
        public string NhanHieu { get; set; }
        public int MaLoai { get; set; }
        public int MaNCC { get; set; }
        public string ThongTinMoTa { get; set; }
        public string HinhAnhChung { get; set; }
        public Nullable<System.DateTime> NgayUpLoad { get; set; }
        public int MaNhomTB { get; set; }
    
        public virtual ICollection<tblChiTietThietBi> tblChiTietThietBi { get; set; }
        public virtual tblLoaiThietBi tblLoaiThietBi { get; set; }
        public virtual tblNhaCungCap tblNhaCungCap { get; set; }
        public virtual tblNhomTB tblNhomTB { get; set; }
    }
}
